### ISSUE TITLE
PlainConnection.write()  sends only part of the data

### ISSUE THREAD

**Issue by phani-vadrevu** [rep/evnet#2]
When I run the code here, calls made from remote clients result only part of the data being sent. Please find the example code here: http://pastie.org/4551609

My config:
Python 2.7.1
Ubuntu 11.04

**Comment by rep** [comment]
Hey, thanks for opening an issue. However I can't reconstruct the problem. For me the pastie works perfectly fine. 

The complete data is sent and received as expected by a webbrowser or a wget. Can you explain your problem a bit more? Which client are you using? 

If you do "wget -O foo http://127.0.0.1:8181/" - is the complete data saved into file "foo"?

**Comment by rep** [comment]
Okay on my system the problem only manifested itself with bigger data amounts. I modified your range(30000) to range(90000) and then also for me the data was truncated.

However I also found the reason for this. In your code you close() directly after send(). In the non-blocking world that does not work as the data is not really sent directly. If the kernel buffers are full evnet will wait until the socket is writable again and then send out the rest of the data. If you close the socket in the meanwhile, then of course the data is truncated.

First you need to remove the call to close. Then what you really should do is tell the client the "Content-Length" you are about to send. Then the client should disconnect after it has all it needs. In case that is not possible for your application, you should close the socket only after being sure that all data was sent. To be honest that is currently a bit tricky in evnet. The Connection class will tell you only just before the buffers are empty that you can write data again (for performance reasons). So what we should probably do is introduce an event "allsent" or something like this that you can use for this purpose.

Summary:
- do not close connections before all data is sent
- only close after buffer is empty

Take a look at an updated version of your paste: http://pastie.org/4555522

**Comment by phani-vadrevu** [comment]
Neat! This works perfectly. Thanks for the code change. 

Out of curiosity, why does a simple time.sleep(10) before closing the connection not work? I was hoping this would yield the same result: http://pastie.org/4557817

**Comment by rep** [comment]
Same problem basically with sleeps, in the non-blocking world this blocks the event loop and no data will be processed / no events will be received. If you need some timeouts / time-based processing, you can use evnet's "later" function.

Something like
from evnet import later
def mytimercb(): print "called after timout"
later(5.0, mytimercb)

**Comment by phani-vadrevu** [comment]
That was interesting! Thanks for working on this issue.
