### ISSUE TITLE
pyev has no version() method

### ISSUE THREAD

**Issue by llimllib** [rep/evnet#6]
My best guess is that it ought to be [abi_version()](http://pythonhosted.org/pyev/pyev.html#pyev.abi_version)?

Also PyPI [appears](https://pypi.python.org/pypi/evnet/1.0-4) to point to version 1.0-4 of the library, instead of 1.0-5.

**Comment by rep** [comment]
i'm pretty sure it had a version() at some point. Anyway, this was just there to decide whether to use the old API of pyev or the new one (0.4 onwards?).

Feel free to remove the check on your setup, I'll figure out what to do in the lib. Btw I'm not using pyev anymore myself, switched over to gevent.

**Comment by llimllib** [comment]
No worries, I got pointed to it from some demo our network guy wanted to run. We removed the check and everything worked fine; just wanted to let you know.
